### PR TITLE
Update render.ts

### PR DESCRIPTION
**Pull request by baoduy**
A fix cannot add properties to the inextensible object issue when running on PRD mode.

### CODE REVIEW

**Comment by streamich** [comment]
What is "PRD" mode?

**Comment by baoduy** [comment]
It is production, I got an error is "cannot add property object is not extensible" with React when running in production. 
However, replace the ` return Object.assign(children.props, data);` to ` return cloneElement(children, Object.assign({}, children.props, data));` is resolve the issue. So I submit this PR.

**Comment by baoduy** [comment]
Hi @streamich 
Just would like to check when this fix shall be released as I'm going to release my component and would like to go with the fix instead keep a copy of version on my local folder?

Thanks and Regards
Duy

**Pull request merged**
